/// Flutter icons More
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  More
///      fonts:
///       - asset: fonts/More.ttf
///
///
///
import 'package:flutter/widgets.dart';

class More {
  More._();

  static const _kFontFam = 'More';
  static const String? _kFontPkg = null;

  static const IconData vector_2_2 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_add_1_1 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_charity_1_1 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_2 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
